repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: ^conda\.recipe/meta\.yaml$
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

# Check linting and style issues
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.11.12"
  hooks:
    - id: ruff-check
      args: ["--fix", "--show-fixes"]
    - id: ruff-format
      exclude: ^(docs)

# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    exclude: ^(docs)

- repo: https://github.com/woodruffw/zizmor-pre-commit
  # Zizmor version.
  rev: v1.8.0
  hooks:
  # Run the linter.
  - id: zizmor
